This file will contain instructions on how to import RM2C data into the sm64ex-alo repo.
First you should always copy the exported folders (/src,/levels,/sound,/text,/textures,/actors) into your repo.
Then make sure you set RM2C inside the makefile to 1
Then to build for PC use this input to terminal: "make clean && make RM2CPC"
Then to build for N64 use this input to terminal: "make clean && make -j4"
By default, due to their high variability and unique names, no actor data will be included from RM2C output, you must
go per actor and either copy data from a custom.model.inc.c file to the model.inc.c file, or change the includes in group files.

Level specific models will go into a folder inside of /actors/ with the name of the level they belong to. You must copy these folders
over to their level folders. The directory should match the target level dir, and not overwrite any files. Textures should be pre written
to the target level directories.

If you have exported custom behaviors, check the /data/ folder for exported custom behaviors with labels, and associated disassembled functions with matching labels.
These are provided for reference only, they must be manually integrated into the repo.

Below are some warnings generated by RM2C during extraction.
It is expected to have many warnings for editor files and for roms with lots of custom content.

******************************************************************************************

Objects without references must have behaviors created for them, be given an existing behavior, or be commented out.

 Level castle_grounds Area 1 has object  Bhv_Custom_0x0040ef64 with no known label.
 Level castle_grounds Area 1 has object  Bhv_Custom_0x00405b80 with no known label.
 Level castle_grounds Area 1 has object  Bhv_Custom_0x130001dc with no known label.
 Level castle_grounds Area 1 has object  Bhv_Custom_0x00403f00 with no known label.
 Level castle_grounds Area 1 has object  Bhv_Custom_0x130006ac with no known label.
 Level castle_grounds Area 1 has object  Bhv_Custom_0x0700ccc0 with no known label.
 Level castle_grounds Area 1 has object  Bhv_Custom_0x0703f180 with no known label.
 Level castle_grounds Area 1 has object  Bhv_Custom_0x0703fdc0 with no known label.
 Level castle_grounds Area 2 has object  Bhv_Custom_0x130006ac with no known label.
 Level castle_grounds Area 2 has object  Bhv_Custom_0x130001dc with no known label.
 Level castle_grounds Area 2 has object  Bhv_Custom_0x0700ccc0 with no known label.
 Level castle_grounds Area 2 has object  Bhv_Custom_0x0703f180 with no known label.
 Level castle_grounds Area 2 has object  Bhv_Custom_0x0703fdc0 with no known label.
 Level castle_grounds Area 3 has object  Bhv_Custom_0x130006ac with no known label.
 Level castle_grounds Area 3 has object  Bhv_Custom_0x130001dc with no known label.
 Level castle_grounds Area 3 has object  Bhv_Custom_0x0700ccc0 with no known label.
 Level castle_grounds Area 3 has object  Bhv_Custom_0x19000280 with no known label.
 Level castle_grounds Area 3 has object  Bhv_Custom_0x0703cce0 with no known label.
 Level castle_grounds Area 3 has object  Bhv_Custom_0x0703fdc0 with no known label.
 Level castle_grounds Area 4 has object  Bhv_Custom_0x0703bfe0 with no known label.
 Level castle_grounds Area 4 has object  Bhv_Custom_0x130006ac with no known label.
 Level castle_grounds Area 4 has object  Bhv_Custom_0x0700ccc0 with no known label.
 Level castle_grounds Area 4 has object  Bhv_Custom_0x130001dc with no known label.
 Level castle_grounds Area 4 has object  Bhv_Custom_0x0703fdc0 with no known label.
 Level castle_grounds Area 4 has object  Bhv_Custom_0x0703cce0 with no known label.
 Level castle_grounds Area 4 has object  Bhv_Custom_0x0702f9e0 with no known label.
******************************************************************************************

New models are detected by comparing the checksums of textures from the specific model.
The comparison models come from an unedited vanilla rom loaded into Rom Manager.
If a model is in this list, it has either an unrecognized ID or a new texture.
If a model is not in this list, it does not guarantee that it is unedited.

 model Null_DL_00400200_ in folder Null_00400200 has a new model or new textures.
 model Null_DL_00401c00_ in folder Null_00401c00 has a new model or new textures.
 model Null_DL_0040ef00_ in folder Null_0040ef00 has a new model or new textures.
 model Null_DL_00405e00_ in folder Null_00405e00 has a new model or new textures.
 model Null_DL_003767d4_ in folder Null_003767d4 has a new model or new textures.
 model custom_DL_0703e040_ in folder custom_0703e040 has a new model or new textures.
 model custom_DL_19000240_ in folder custom_19000240 has a new model or new textures.
 model custom_DL_19000260_ in folder custom_19000260 has a new model or new textures.
 model custom_DL_19000400_ in folder custom_19000400 has a new model or new textures.
 model custom_DL_19000300_ in folder custom_19000300 has a new model or new textures.
 model custom_DL_19000340_ in folder custom_19000340 has a new model or new textures.
 model unk_DL_04008090_ in folder unk_castle_grounds_04008090 has a new model or new textures.

Known methods of crashing:
*****************************************************************************
ALL BUILDS
IF CRASH ON BOOT - CHECK SEQUENCES
IF TITLE SCREEN LOOP - CHECK START LEVEL IN TWEAKS.H
IF TEXTURES ARE MESSED UP - ALWAYS CHECK LEVEL FOG FIRST
IF ONLY ALPHA TEXTURES MESSED UP - MOVE FOG GEO LAYOUT TO LAYER 1/4 FROM 4/6
IF CRASH UPON ENTERING A LEVEL, CHECK OBJECTS. IF EDITOR, CHECK SCROLLS FIRST. IF NO OBJECTS BAD CHECK SKYBOXES, THEN SEQUENCES
*****************************************************************************
